env:
  browser: true
  commonjs: true
  es6: true
extends: ['plugin:react/recommended','eslint:recommended']
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  react/jsx-uses-vars:
    - error
